# This is a template for a source file containing metadata about a publication that provides experimental/computational
# data or EoS parameters for a given material.
# unique_id should be a short identifier for the source, e.g. "miozzi2020", which is used to link this source metadata
# to the corresponding EOS metadata in template_eos.toml and any thermo metadata in template_thermo.toml.

unique_id = "template2026"  # This should be replaced with a unique identifier e.g. "miozzi2020"
citation = ""  # This should be replaced with the full citation for the source of the EOS, e.g. "Miozzi et al. (2020)"
year = 2026  # This should be replaced with the publication year of the source, e.g. 2020
doi=""  # This should be replaced with the DOI for the source of the EOS, e.g. "10.1234/example.doi"